version: "2.3"

services:

  vehicle:

    image: tensorflow/serving:latest-gpu

    volumes:
      - type: bind
        source: ../data/yolov3-spp
        target: /models/yolov3-spp

    container_name: vehicle-detector

    runtime: nvidia

    ports:
      - 8500:8500 # HTTP/REST API
      - 8501:8501 # gRPC

    environment:
      MODEL_NAME: yolov3-spp


  plate:

    image: tensorflow/serving:latest-gpu

    volumes:
      - type: bind
        source: ../data/lp-detector
        target: /models/lp-detector

    container_name: plate-detector

    runtime: nvidia

    ports:
      - 8502:8500 # HTTP/REST API
      - 8503:8501 # gRPC

    environment:
      MODEL_NAME: lp-detector


  liscense:

    image: tensorflow/serving:latest-gpu

    volumes:
      - type: bind
        source: ../data/ocr
        target: /models/ocr

    container_name: ocr

    runtime: nvidia

    ports:
      - 8504:8500 # HTTP/REST API
      - 8505:8501 # gRPC

    environment:
      MODEL_NAME: ocr
